### PR TITLE
146 update sifted for stage overhaul

### PR DESCRIPTION
**Pull request by CZLam7**
Currently two things still pending (or I'm just unsure atm): 

1. I haven't update the testing, as now calling sifted has to use output from prelim. Perhaps I should update after the prelim's merged? Also the argument I use in Sifted is data_dense: Data, not DataDense class created by Kian as it hasn't been merged and I can't use it. 
2. Sifted change almost everything in Data class (the old one), how does these changes reflect if SiftedDataChanged has been removed?

### CODE REVIEW

**Review by KushagraKhare0 — CHANGES_REQUESTED** [review]
Great job in adopting the new scaffold, there are some issues that need to be addressed in both sifted_test and also linter errors - I understand that you are waiting on prelim but it would be great if you can the errors "poe check"

**Review by neatht — CHANGES_REQUESTED** [review]
You need to merge #130 into your branch.

**Review by neatht — CHANGES_REQUESTED** [review]

**Review by neatht — CHANGES_REQUESTED** [review]
Still a lot of mypy errors. I recomend the VSCode mypy (and ruff) extension so it underlines the offending code while you are coding.

**Review by neatht — APPROVED** [review]
The only poe errors appear to be in test_sifted, which needs to be fixed but it won't block me from doing the integration, so approved.

**Review by neatht — CHANGES_REQUESTED** [review]

**Review by KushagraKhare0 — APPROVED** [review]
Comments have been addressed

**Review by neatht — APPROVED** [review]

**Pull request merged**
