### PR TITLE
Trace Completed

### PR DESCRIPTION
**Pull request by ybguzel**
Trace is completed and the tests are checked with the client. The stage outputs the required analysis. The client's request to change dbscan to hdbscan is postponed until later.

### CODE REVIEW

**Review by KushagraKhare0 — COMMENTED** [review]
Great job with the implementation, I would recommend addressing my comments to help with the poetry errors

**Review by dhjang03 — CHANGES_REQUESTED** [review]
Great work migrating Trace

**Review by KushagraKhare0 — DISMISSED** [review]
All comments have been addressed, I don't see any other issue

**Review by KushagraKhare0 — COMMENTED** [review]
You need to change the tests to be able to test the trace_stage against its matlab version quantitatively

**Review by Hazel-Yi — COMMENTED** [review]
Eyyy nicely done~
just a few comment regarding the test

**Review by Taozizz — COMMENTED** [review]
Add checking the result of python implementation & matlab implementation

**Review by neatht — CHANGES_REQUESTED** [review]
See above comment

**Pull request closed without merging**
