### PR TITLE
211 sifted documentation needs completing

### LINKED ISSUE #211: Sifted documentation needs completing

### PR DESCRIPTION
**Pull request by CZLam7**

### CODE REVIEW

**Review by neatht — APPROVED** [review]
Good work on docs, but there seems to be a bunch of code changes. do you need to merge dev?

**Review by KIAND-glitch — CHANGES_REQUESTED** [review]
This PR is attempted to merge into main, and has changes to other files that are not Sifted documentation related, can we please change to development

**Review by KIAND-glitch — APPROVED** [review]
Looks goods

**Review by neatht — CHANGES_REQUESTED** [review]
Get passing poe checks first.

**Review by neatht — APPROVED** [review]

**Pull request merged**
